/**
 * Reading CloudCannon's shipped packages: locating them, installing the pinned
 * versions, and parsing the two artifacts that describe their public surface.
 *
 * `check-claims.mjs` and `diff-surface.mjs` both read these and have to agree:
 * two scripts parsing `documentation.json` differently would be the drift they
 * exist to catch.
 *
 * Nothing here executes the packages — they are read as data, so neither script
 * inherits an engine constraint or a dependency.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve, extname } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const SKILLS = join(ROOT, "skills");

export const CLI_PKG = "@cloudcannon/cli";
export const SDK_PKG = "@cloudcannon/sdk";

/**
 * The versions the claims were verified against, and the versions `--install`
 * installs — one declaration in package.json, so the two cannot drift.
 */
export const PINS = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).documentedPackages;

/* --- Locating and installing --- */

/** The package's directory under `root`, or null if it is not installed there. */
export function packageDir(name, root) {
  const dir = join(root, "node_modules", ...name.split("/"));
  return existsSync(join(dir, "package.json")) ? dir : null;
}

export function versionOf(dir) {
  return JSON.parse(readFileSync(join(dir, "package.json"), "utf8")).version;
}

/**
 * Installs `specs` under a temp prefix and returns it. Outside the repo,
 * always: installing into this tree re-resolves its own devDependencies, which
 * can move prettier a minor version and reformat unrelated files.
 */
export function installPackages(specs, label) {
  const prefix = join(tmpdir(), label);
  // npm blocks on a non-terminal stdin, hanging under CI and any piped run.
  execFileSync("npm", ["install", "--prefix", prefix, "--no-audit", "--no-fund", ...specs], {
    stdio: ["ignore", "inherit", "inherit"],
  });
  return prefix;
}

/** The pinned versions of both packages, under one prefix. */
export function installPinned(label = "agent-skills-claims") {
  return installPackages(
    Object.entries(PINS).map(([name, version]) => `${name}@${version}`),
    label,
  );
}

/** The newest version on the registry. */
export function latestVersion(name) {
  return execFileSync("npm", ["view", name, "version"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  }).trim();
}

/* --- The CLI's surface --- */

/**
 * Every leaf CLI command, keyed by its path without the `cloudcannon ` prefix,
 * mapped to its flag names.
 *
 * `documentation.json` is generated by the CLI itself and shipped as a declared
 * export, so this is the CLI describing itself rather than us guessing.
 */
export function readCliCommands(cliDir) {
  const doc = JSON.parse(readFileSync(join(cliDir, "dist", "documentation.json"), "utf8"));
  const byPath = new Map();
  const walk = (arr) => {
    for (const c of arr || []) {
      if (c.subCommands?.length) walk(c.subCommands);
      else
        byPath.set(
          c.fullName.replace(/^cloudcannon\s+/, ""),
          new Set((c.options || []).map((o) => o.name)),
        );
    }
  };
  walk(doc.subCommands);
  return byPath;
}

/* --- The SDK's surface --- */

/** Sub-client name → the generated `.d.ts` that declares it. */
export const SDK_FILES = {
  root: "index.d.ts",
  org: "src/org.d.ts",
  site: "src/site.d.ts",
  editingSession: "src/editing-session.d.ts",
  editingSessionFile: "src/editing-session-file.d.ts",
  build: "src/build.d.ts",
  sync: "src/sync.d.ts",
  backup: "src/backup.d.ts",
  inbox: "src/inbox.d.ts",
  siteInbox: "src/site-inbox.d.ts",
};

/** Method names declared on a sub-client, read from its generated `.d.ts`. */
export function readSdkMethods(sdkDir, file) {
  const src = readFileSync(join(sdkDir, "dist", file), "utf8");
  // `[<(]` catches a generic method: `fetch<const U ...>(` has nested angle
  // brackets, so nothing can match across to its closing `>`.
  const names = new Set(
    [...src.matchAll(/^ {4}(?:readonly\s+)?([a-zA-Z_]\w*)\s*[<(]/gm)].map((m) => m[1]),
  );
  names.delete("constructor");
  return names;
}

/** Every sub-client's methods, keyed as the skills' prose refers to them. */
export function readSdkClients(sdkDir) {
  return Object.fromEntries(
    Object.entries(SDK_FILES).map(([client, file]) => [client, readSdkMethods(sdkDir, file)]),
  );
}

/* --- Reading the skills --- */

export function walkMarkdown(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walkMarkdown(full, out);
    else if (extname(full) === ".md") out.push(full);
  }
  return out;
}

/* --- Argv --- */

/** `--name value` or `--name=value`. */
export function flagValue(argv, name) {
  const i = argv.indexOf(`--${name}`);
  if (i !== -1) return argv[i + 1];
  return argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);
}
